on:
  push:
    branches:
        - feature/AzureSQLIntegration 
jobs:
    build-sql-scripts:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8'
        
        - name: Build Sql Script
          run: dotnet ef migrations script --idempotent -o ./SqlScripts/BaseSql.sql
        
    deploy-sql-scripts:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: azure/sql-action@v2.3
          with:
            connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
            path: './SqlScripts/BaseSql.sql'

