on:
  push:
    branches:
        - feature/AzureSQLIntegration 
jobs:
    build-sql-scripts:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8'
        
        #   continue-on-error: true
        
        - name: Build Sql Script
          run: |
            dotnet tool install --global dotnet-ef
            cd ./FinalProject1/
            dotnet ef migrations script --idempotent -o ./SqlScripts/BaseSql.sql
            echo "Checking Working Directory..."
            ls
        
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: .net-script
            path: ./SqlScripts/BaseSql.sql



    # deploy-sql-scripts:
    #     needs: build-sql-scripts
    #     runs-on: ubuntu-latest
    #     steps:
    #     - uses: actions/checkout@v3
    #     - uses: azure/sql-action@v2.3
    #       with:
    #         connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
    #         path: './SqlScripts/BaseSql.sql'

